#!/bin/sh
##echo "$1 $2 $3"
docker run -v $PWD:/container/ -it aitwatchman/simulation:bonsai  /src/rat-pac/tools/bonsai/bonsai /container/$1 /container/$2 /container/$3 /container/$4 /container/$5 /container/$6
